background_opacity 0.8
background      #020002
foreground      #ff8fdd
#alt background #1d0020

font_family      Nimbus Mono PS
bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size  13

selection_background       #ff99e0
selection_foreground       #111111      
cursor                     #ffffff
url_color                  #fb91ff
   

# terminal colors

#black
color0                      #38013f
color8                      #f396ff

#red
color1                      #ff52ba
color9                      #ff99e0

#green
color2                      #d782ff
color10                     #ebbdff

#yellow
color3                      #ff97da
color11                     #ffcfed

#blue
color4                      #a642d5
color12                     #eeacff

#magenta
color5                      #ff6dc2
color13                     #ffbbe6

#cyan
color6                      #ff50b3
color14                     #fa71ff

#white
color7                      #ffa6de
color15                     #ffffff

